######################################################################
# Automatically generated by qmake (3.0) Sat Apr 4 16:43:22 2015
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += . hpp TestCases src/gcpp.0
CONFIG += c++11

# Input
HEADERS += manifest.hpp \
           hpp/bootstrap.hpp \
           hpp/registery.hpp \
           hpp/testCase.hpp \
           hpp/teststrap.hpp \
           src/gcpp.hpp \
           TestCases/gcppStub.hpp \
           TestCases/gcppTestCaser.hpp \
           src/gcpp.0/fastvec.hpp \
           src/gcpp.0/gc.hpp \
           src/gcpp.0/gcafx.hpp \
           src/gcpp.1/gc.hpp \
           src/gcpp.1/gc_array_ptr.hpp \
           src/gcpp.1/gc_cast.hpp \
           src/gcpp.1/gc_detail.hpp \
           src/gcpp.1/gc_map.hpp \
           src/gcpp.1/gc_ptr.hpp \
           src/gcpp.1/gcafx.hpp
SOURCES += testerMain.cpp src/gcpp.0/gcpp.cpp
